---
title:               鸣叫的山河夜叉
tagline:             重剑无锋大巧不工
excerpt_separator: <!--more-->
future:              true
paginate:            5
baseurl:             ""
permalink:           pretty


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Julien LU
  url:               https://twitter.com/lxxdn
  email:             julien.luxiao@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/lxxdn

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

---
